export const categories = [
  { name: "Top 100", category: "top-100", link: "top-100-songs.php" },
  { name: "Alternative", category: "alternative", link: "top-alternative-songs.php" },
  { name: "BlueGrass", category: "bluegrass", link: "top-bluegrass-songs.php" },
  { name: "Blues", category: "blues", link: "top-blues-songs.php" },
  { name: "Christian", category: "christian", link: "top-christian-gospel-songs.php" },
  { name: "Country", category: "country", link: "top-country-songs.php" },
  { name: "Dance", category: "dance", link: "top-dance-songs.php" },
  { name: "Electronic", category: "electronic", link: "top-electronic-songs.php" },
  { name: "Heavy Metal", category: "heavy-metal", link: "top-heavy-metal-songs.php" },
  { name: "Indie Rock", category: "indie-rock", link: "top-indie-songs.php" },
  { name: "Jazz", category: "jazz", link: "top-jazz-songs.php" },
  { name: "K Pop", category: "k-pop", link: "top-kpop-songs.php" },
  { name: "Kids", category: "kids", link: "top-kids-songs.php" },
  { name: "Latin", category: "latin", link: "top-latin-songs.php" },
  { name: "Pop", category: "pop", link: "top-pop-songs.php" },
  { name: "Soul", category: "soul", link: "top-soul-songs.php" },
  { name: "Rap", category: "rap", link: "top-rap-songs.php" },
  { name: "Reggae", category: "reggae", link: "top-reggae-songs.php" },
  { name: "Reggaeton", category: "reggaeton", link: "top-reggaeton-songs.php" },
  { name: "Rock", category: "rock", link: "top-rock-songs.php" },
  { name: "SoundTrack", category: "soundtrack", link: "top-soundtrack-songs.php" },
];
